function displayRules() { 
    const rulesDiv = document.createElement('div');
    rulesDiv.classList.add('rules-div');
    rulesDiv.id = 'rules-div';
    const rulesHeader = document.createElement('h2');
    rulesHeader.classList.add('rules-header');
    rulesHeader.id = 'rules-header';
    rulesHeader.textContent = 'Rules';
    const rulesList = document.createElement('ul');
    rulesList.classList.add('rules-list');
    rulesList.id = 'rules-list';
    const rule1 = document.createElement('li');
    rule1.classList.add('rule1');
    rule1.id = 'rule1';
    rule1.textContent = 'Any live cell with fewer than two live neighbours dies, as if by underpopulation.';
    const rule2 = document.createElement('li');
    rule2.classList.add('rule2');
    rule2.id = 'rule2';
    rule2.textContent = 'Any live cell with two or three live neighbours lives on to the next generation.';
    const rule3 = document.createElement('li');
    rule3.classList.add('rule3');
    rule3.id = 'rule3';
    rule3.textContent = 'Any live cell with more than three live neighbours dies, as if by overpopulation.';
    const rule4 = document.createElement('li');
    rule4.classList.add('rule4');
    rule4.id = 'rule4';
    rule4.textContent = 'Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.';
    rulesList.appendChild(rule1);
    rulesList.appendChild(rule2);
    rulesList.appendChild(rule3);
    rulesList.appendChild(rule4);
    rulesDiv.appendChild(rulesHeader);
    rulesDiv.appendChild(rulesList);
    //return rulesDiv;
    const StartGameBtn = document.createElement('button');
    StartGameBtn.classList.add('start-game-btn');
    StartGameBtn.id = 'start-game-btn';
    StartGameBtn.textContent = 'Start Game';
    rulesDiv.appendChild(StartGameBtn);
    const content = document.getElementById('content');
    content.appendChild(rulesDiv);
}
export default displayRules;